# Generated by Django 6.1 on 2026-08-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
