# Generated by Django 6.1 on 2026-08-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_staffuser_full_name_staffuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
