# Generated by Django 6.1 on 2026-08-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_brand_name_booking_model_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingphoto',
            name='photo_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
