# Generated by Django 6.1 on 2026-08-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookingphoto_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
