# Generated by Django 6.1 on 2026-08-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_job_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cert_code',
            field=models.CharField(blank=True, help_text='Human-readable certificate reference e.g. TL-N955-HAJW', max_length=50, null=True, unique=True),
        ),
    ]
