# Generated by Django 6.1 on 2026-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_certificate_cert_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='selected_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of selected photo IDs for display on certificate'),
        ),
    ]
