# Generated by Django 6.1 on 2026-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_certificate_selected_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
