# Generated by Django 6.1 on 2026-08-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customer_user_alter_staffuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='promptpay', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('slip_photo', models.ImageField(blank=True, null=True, upload_to='slips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to='api.customer')),
            ],
            options={
                'db_table': 'topup_requests',
            },
        ),
    ]
