# Generated by Django 6.1 on 2026-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_topuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, default='BAG', max_length=50),
        ),
    ]
