# Generated by Django 6.1 on 2026-09-15 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_method',
            field=models.CharField(choices=[('self_pickup', 'มารับด้วยตัวเอง'), ('shipping', 'จัดส่งพัสดุ')], default='self_pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_address_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_address_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_subdistrict',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('corporate', 'Corporate')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum outstanding postpaid balance', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='postpaid_enabled',
            field=models.BooleanField(default=False, help_text='Allow corporate postpaid (inspect-now, pay-later)'),
        ),
        migrations.AddField(
            model_name='job',
            name='cancel_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='service_package',
            field=models.CharField(choices=[('cert_15d', 'ตรวจสอบ + ใบรับรอง 15 วัน'), ('cert_90d', 'ตรวจสอบ + ใบรับรอง 90 วัน'), ('photo_review', 'ตรวจสอบผ่านรูปภาพ (Photo Review)')], default='cert_90d', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='shipping_status',
            field=models.CharField(choices=[('not_applicable', 'มารับเอง'), ('pending_return', 'รอจัดส่งคืน'), ('ready_to_ship', 'เตรียมจัดส่งแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ลูกค้ารับแล้ว')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='VAT 7% amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('transfer', 'Bank Transfer'), ('promptpay', 'PromptPay QR'), ('postpaid', 'Corporate Postpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('invoiced', 'Invoiced (Postpaid)')], default='unpaid', max_length=20),
        ),
    ]
