# Generated by Django 6.1 on 2026-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_seed_service_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='evidence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
