# Generated by Django 6.1 on 2026-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_topuprequest_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
