# Generated by Django 6.1 on 2026-09-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fix_gold_platinum_swap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
        migrations.AlterField(
            model_name='job',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
    ]
