# Generated by Django 6.1 on 2026-09-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_cancellationrequest_booking_alter_job_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
